version: '3.4'

services:
  postgres:
    image: postgres:15.1
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "5432:5432"
  newsportal.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://*:443
    ports:
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro